name: Node CI for Pull Request

on: [pull_request]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout [${{ github.event.pull_request.head.ref }}]
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install
        run: npm ci
        env:
          CI: true
      - name: Start NX Cloud CI
        run: npx nx-cloud start-ci-run
      - name: Build
        run: npm run build:ci
        env:
          CI: true
      - name: Test
        run: npm run test:ci
        env:
          CI: true
      - name: Stop NX Cloud agents
        run: npx nx-cloud stop-all-agents
